### ISSUE TITLE
System Requirements

### ISSUE THREAD

**Issue by momin-ahmad-khan** [FLAIR-THU/CreamFL#3]
Hi, could you tell me what are the system requirements for this code. Number of gpus, and memory of each gpu. Also, what was the average training time for the experiments. 
I am trying to run this on a 12GB gpu but it runs out of memory.
Thanks.

**Comment by yqy2001** [comment]
We use one A100-40G GPU with each run takes about one day.

12G memory is not enough, but you can try to reduce the number or dim of public data and conduct experiments in a your memory-affordable setting.

Thank you.

**Comment by momin-ahmad-khan** [comment]
Thank you!
